# Example Pester-only pipeline with concurrent jobs via unified actionGroups

parameters:
  - name: runUnit
    type: boolean
    default: false
  - name: runIntegration
    type: boolean
    default: false
  - name: runRegression
    type: boolean
    default: false
  - name: runSmoke
    type: boolean
    default: false
  - name: drInvocation
    type: boolean
    default: false

trigger:
  branches:
    include: ['*']

pr:
  branches:
    include: ['*']

extends:
  template: pester.settings.yml
  parameters:
    drInvocation: ${{ parameters.drInvocation }}
    actionGroups:
      - name: unit
        type: powershell
        enabled: ${{ parameters.runUnit }}
        actions:
          - name: unit
            scriptPath: scripts/pester_run.ps1
            arguments: "-TestsPath examples/assets/tests/pester/unit -ResultsFile TestResults/pester.unit.xml"
      - name: integration
        type: powershell
        enabled: ${{ parameters.runIntegration }}
        actions:
          - name: integration
            scriptPath: scripts/pester_run.ps1
            arguments: "-TestsPath examples/assets/tests/pester/integration -ResultsFile TestResults/pester.integration.xml"
      - name: regression
        type: powershell
        enabled: ${{ parameters.runRegression }}
        actions:
          - name: regression
            scriptPath: scripts/pester_run.ps1
            arguments: "-TestsPath examples/assets/tests/pester/regression -ResultsFile TestResults/pester.regression.xml"
      - name: smoke
        type: powershell
        enabled: ${{ parameters.runSmoke }}
        actions:
          - name: smoke
            scriptPath: scripts/pester_run.ps1
            arguments: "-TestsPath examples/assets/tests/pester/smoke -ResultsFile TestResults/pester.smoke.xml"

# Example schedule (regression)
# schedules:
#   - cron: "0 1 * * 1-5"
#     displayName: Nightly Regression
#     branches:
#       include: [ main ]
#     always: true
